services:
  proxy:
    image: nginx:1.21.6-alpine
    volumes:
      - ./proxy:/etc/nginx/templates
    ports:
      - "80:80"

  frontend:
    build: frontend
    depends_on:
      - proxy
    env_file:
      - variables.env 

  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  login:
    build: LoginService
    depends_on:
      - postgres
    env_file:
      - variables.env
      
volumes:
  postgres-data:
    driver: local